"""Generation of the C ABI layer linking Python to the Verilator model."""

from __future__ import annotations

from .profile import BoardProfile


def render_cpp_wrapper(profile: BoardProfile, model_class: str = "Vtop") -> str:
    """Create an unmangled API: init/reset/eval and per-port reads/writes."""
    observed_bits = profile.observed_bits
    if len(observed_bits) > 64:
        raise ValueError("La sonda temporal base admite hasta 64 bits de salida.")
    observed_reads = ",\n        ".join(
        f"static_cast<uint8_t>((g_top->{name} >> {bit}) & 1U)"
        for name, bit in observed_bits
    ) or "0"
    setters = "\n".join(
        f"void sim_set_{name}(uint64_t value) {{ if (g_top) g_top->{name} = value; }}"
        for name in profile.inputs
        if name != profile.clock_name
    )
    getters = "\n".join(
        f"uint64_t sim_get_{name}() {{ return g_top ? static_cast<uint64_t>(g_top->{name}) : 0; }}"
        for name in profile.outputs
    )
    return f'''// Generated by FPGALab. Do not edit: update board_profile.json.
#include "{model_class}.h"
#include "verilated.h"
#include <cstdint>

static {model_class}* g_top = nullptr;
static VerilatedContext* g_context = nullptr;
static constexpr uint32_t kObservedCount = {len(observed_bits)};
static uint8_t g_observed_previous[kObservedCount ? kObservedCount : 1] = {{0}};
static uint8_t g_observed_start[kObservedCount ? kObservedCount : 1] = {{0}};
static uint8_t g_observed_end[kObservedCount ? kObservedCount : 1] = {{0}};
static uint64_t g_observed_high_halves[kObservedCount ? kObservedCount : 1] = {{0}};
static uint64_t g_observed_edges[kObservedCount ? kObservedCount : 1] = {{0}};
static uint64_t g_observed_samples = 0;
static uint64_t g_observation_divisor = 12;

static void sample_observed(bool first) {{
    ++g_observed_samples;
    const uint8_t values[kObservedCount ? kObservedCount : 1] = {{
        {observed_reads}
    }};
    for (uint32_t index = 0; index < kObservedCount; ++index) {{
        if (first) g_observed_start[index] = values[index];
        else if (values[index] != g_observed_previous[index]) ++g_observed_edges[index];
        g_observed_previous[index] = values[index];
        g_observed_end[index] = values[index];
        g_observed_high_halves[index] += values[index];
    }}
}}

static void reset_observation() {{
    g_observed_samples = 0;
    for (uint32_t index = 0; index < kObservedCount; ++index) {{
        g_observed_start[index] = g_observed_previous[index];
        g_observed_end[index] = g_observed_previous[index];
        g_observed_high_halves[index] = 0;
        g_observed_edges[index] = 0;
    }}
}}

extern "C" {{

void init_sim() {{
    if (g_top) return;
    g_context = new VerilatedContext;
    g_top = new {model_class}{{g_context}};
    g_top->{profile.clock_name} = 0;
    g_top->eval();
    sample_observed(true);
}}

void reset_sim() {{
    if (!g_top) init_sim();
    g_top->final();
    delete g_top;
    delete g_context;
    g_top = nullptr;
    g_context = nullptr;
    init_sim();
}}

void close_sim() {{
    if (!g_top) return;
    g_top->final();
    delete g_top;
    delete g_context;
    g_top = nullptr;
    g_context = nullptr;
}}

void eval_sim() {{ if (g_top) g_top->eval(); }}
void sim_set_clk(uint8_t value) {{ if (g_top) g_top->{profile.clock_name} = value ? 1 : 0; }}
uint8_t sim_get_clk() {{ return g_top ? static_cast<uint8_t>(g_top->{profile.clock_name}) : 0; }}
void step_clock() {{
    if (!g_top) init_sim();
    g_top->{profile.clock_name} = 1; g_top->eval();
    g_top->{profile.clock_name} = 0; g_top->eval();
    g_context->timeInc(1);
}}
void run_cycles(uint64_t cycles) {{
    if (!g_top) init_sim();
    reset_observation();
    uint64_t remaining = 0;
    for (uint64_t cycle = 0; cycle < cycles; ++cycle) {{
        const bool observe = remaining == 0;
        g_top->{profile.clock_name} = 1; g_top->eval(); if (observe) sample_observed(cycle == 0);
        g_top->{profile.clock_name} = 0; g_top->eval();
        if (observe) {{
            sample_observed(false);
            remaining = g_observation_divisor - 1;
        }} else --remaining;
    }}
    // Synthesizable FPGA designs do not use #delay or $time: advancing the
    // context once per batch removes one non-inline call per cycle.
    g_context->timeInc(cycles);
}}

uint32_t sim_observed_count() {{ return kObservedCount; }}
uint64_t sim_observed_samples() {{ return g_observed_samples; }}
void sim_set_observation_divisor(uint64_t value) {{ g_observation_divisor = value ? value : 1; }}
uint8_t sim_observed_start(uint32_t index) {{ return index < kObservedCount ? g_observed_start[index] : 0; }}
uint8_t sim_observed_end(uint32_t index) {{ return index < kObservedCount ? g_observed_end[index] : 0; }}
uint64_t sim_observed_high_halves(uint32_t index) {{ return index < kObservedCount ? g_observed_high_halves[index] : 0; }}
uint64_t sim_observed_edges(uint32_t index) {{ return index < kObservedCount ? g_observed_edges[index] : 0; }}

{setters}

{getters}

}} // extern "C"
'''
