"""Non-invasive discovery of artifacts generated by Icestudio."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


class IcestudioProjectError(RuntimeError):
    """The selected design has no executable Icestudio artifacts."""


@dataclass(frozen=True)
class IcestudioProject:
    """An ``.ice`` design and its matching ``ice-build`` subdirectory."""

    ice_file: Path
    build_dir: Path
    main_v: Path
    pcf: Path | None

    @classmethod
    def discover(cls, ice_file: str | Path) -> "IcestudioProject":
        source = Path(ice_file).expanduser().resolve()
        if not source.is_file() or source.suffix.lower() != ".ice":
            raise IcestudioProjectError("Select an Icestudio design file (.ice).")

        root = source.parent / "ice-build"
        preferred = root / source.stem
        candidates = (preferred, root)
        for directory in candidates:
            main_v = directory / "main.v"
            if main_v.is_file():
                pcf = cls._constraints_in(directory)
                return cls(source, directory, main_v, pcf)

        expected = preferred / "main.v"
        raise IcestudioProjectError(
            f"{expected} does not exist. Generate Verilog from Icestudio before running."
        )

    @staticmethod
    def _constraints_in(directory: Path) -> Path | None:
        for name in ("main.pcf", "main.xdc"):
            candidate = directory / name
            if candidate.is_file():
                return candidate
        candidates = sorted((*directory.glob("*.pcf"), *directory.glob("*.xdc")))
        return candidates[0] if len(candidates) == 1 else None

    @property
    def constraints_path(self) -> Path | None:
        """Physical pin assignments (the legacy field is named pcf)."""
        return self.pcf

    @property
    def sources(self) -> tuple[Path, ...]:
        return (self.main_v,) if self.pcf is None else (self.main_v, self.pcf)

    @property
    def lab_file(self) -> Path:
        """Return the FPGALab sidecar path, kept outside Icestudio artifacts."""
        return self.ice_file.parent / ".fpgalab" / f"{self.ice_file.stem}.lab.json"

    def ensure_lab_file(self) -> Path:
        """Create an empty laboratory sidecar on first use and return it."""
        lab_file = self.lab_file
        if not lab_file.exists():
            lab_file.parent.mkdir(parents=True, exist_ok=True)
            lab_file.write_text('{\n  "peripherals": []\n}\n', encoding="utf-8")
        return lab_file
